### ISSUE TITLE
Update branch protection rules in our repos

### ISSUE THREAD

**Issue by santisoler** [fatiando/community#117]
**Description:**

The `main` branch of most of our repos are protected against direct pushes by requiring that every push must be carried out through a PR. This enforces contributors, developers and maintainers to open a PR for every change, even if it's small. This ensures that the code in every commit in `main` is tested and passes all tests, documentation builds properly, and the change is explained and linked to a PR with a good narrative and discussion.
It also prevents that contributors with writing privileges push changes to `main` by mistake (we've all been there).

But, recently GitHub changed the default behaviour of the branch protection rules, making admins able to bypass all of them, pushing directly to `main` included. So now, even if the condition to _Require a pull request before merging_ is checked off, admins **can** push directly to main.

One way to solve this is to check off a new box called _Do not allow bypassing the above settings_, that won't allow admins to bypass these rules.

I'm attaching a screen capture of the branch protection rules in Harmonica, highlighting the box we need to check.

![github](https://github.com/fatiando/community/assets/11541317/ee41772b-0d6f-4acd-861e-2e6c76e74c94)

I think we need to apply these changes to all our repos, mainly to prevent ourselves pushing to `main` by mistake.

**Apply to:**

- [x] [boule](https://github.com/fatiando/boule)
- [x] [harmonica](https://github.com/fatiando/harmonica)
- [x] [pooch](https://github.com/fatiando/pooch)
- [x] [verde](https://github.com/fatiando/verde)
- [x] [ensaio](https://github.com/fatiando/ensaio)
- [x] [choclo](https://github.com/fatiando/choclo)
- [x] [dependente](https://github.com/fatiando/dependente)
- [x] [website](https://github.com/fatiando/website)
- [x] [tutorials](https://github.com/fatiando/tutorials)
- [x] [community](https://github.com/fatiando/community)
- [x] [.github](https://github.com/fatiando/.github)

**We want your help!**

We know that maintenance tasks are very demanding, so we don't expect a single person to tackle this issue by themselves. Any help is very welcomed, so please comment below that you want to take care of the changes on any repository and we will assign it to you.

**Comment by LL-Geo** [comment]
Getting a boring meeting... So I clicked all the boxes🤣 
Hope it solved the issue :)

**Comment by santisoler** [comment]
🤯 That's awesome @LL-Geo! I think we can close this then. Thank you very much!

**Comment by leouieda** [comment]
Love this! First seeing the issue and it's already closed 🙂 Thanks @LL-Geo

**Comment by MGomezN** [comment]
Great job @LL-Geo 
I was struggling with the difference between _"check off"_ and _"check"_ in the instructions:
  _"One way to solve this is to check off"_ / _" highlighting the box we need to check."_

**Comment by santisoler** [comment]
> I was struggling with the difference between "check off" and "check" in the instructions:
"One way to solve this is to check off" / " highlighting the box we need to check."

I think I meant "check off" in the second sentence as well. Please, don't take my English as always right 🥲
