### ISSUE TITLE
Add another point of contact to the Code of Conduct

### ISSUE THREAD

**Issue by leouieda** [fatiando/community#29]
Right now, the only point of contact for reporting a violation of the CoC is me. This is really not ideal and it would be good to have at the very least 1 more person there (preferably 2). 

Any volunteers, please let me know in the comments below.

**Comment by santisoler** [comment]
I can volunteer to be another contact for any CoC violations.
As always, would be nice to have some diversity here too.

cc @aguspesce @andieie

**Comment by aguspesce** [comment]
@leouieda and @santisoler. I don't have problem, you can add my name

**Comment by leouieda** [comment]
🎉  thanks, both
