### ISSUE TITLE
Create fatiando metapackage

### ISSUE THREAD

**Issue by santisoler** [fatiando/community#31]
**Description**

Would be nice to publish a `fatiando` metapackage to PyPI and conda-forge so any user can install the latest release of all Fatiando a Terra libraries on a single line, as we used to install the old `fatiando` package:

```
pip install fatiando
```

```
conda install -c conda-forge fatiando
```

When doing so we should update the docs of `fatiando` v0.5 so anyone interested using the old package can still use it.

**Comment by leouieda** [comment]
Giving up on this to avoid problems with people looking for the old Python 2.7 package. It's better if they get an error instead.
