### ISSUE TITLE
Extend support for Python 3.9

### ISSUE THREAD

**Issue by santisoler** [fatiando/community#36]
**Description**

Being Python 3.9 the latest major release, Fatiando libraries should support it too.
There's no much work to do so, we would need to expand the automated tests on CIs to Python 3.9, add 3.9 to the `setup.py` and check if every test pass.

**Apply changes to**

Libraries:

- [x] [boule](https://github.com/fatiando/boule)
- [x] [harmonica](https://github.com/fatiando/harmonica)
- [x] [pooch](https://github.com/fatiando/pooch)
- [x] [verde](https://github.com/fatiando/verde)

**Further instructions**

In order to solve this issue we need to start opening Pull Requests on each
repository listed above. Optionally, we can open Issues on each repository if
further discussion specific to that repository is needed.

Remember to mention this Issue on every Issue or Pull Request opened on each
repository for keeping a record by adding something like:

```
Related to fatiando/maintenance#14
```

A quick checklist:

1. Open an Issue on each repository listed above (optional). Mention this Issue
   on them.
2. Open a Pull Request on the same repository to tackle the Issue. Mention this
   Issue on them.
3. Check-off the repository on the list above once the Pull Request is merged.
4. Close this issue when all items are checked-off.

**We want your help**

We know that maintenance tasks are very demanding, so we don't expect a single
person to tackle this issue by themselves. Any help is very welcomed, so please
comment below that you want to take care of the changes on any repository and
we will assign it to you.

**Comment by hugovk** [comment]
Boule done in https://github.com/fatiando/boule/pull/87

**Comment by leouieda** [comment]
Thanks @hugovk, I missed that when transferring issues.
